@echo off
setlocal EnableDelayedExpansion

:: Set output file name with date stamp (e.g., Personal_Info_20250411.txt)
set "dateStamp=%date:~10,4%%date:~4,2%%date:~7,2%"
set "outputFile=Personal_Info_%dateStamp%.txt"

:: Redirect all output to file at once for speed and silence
(
    :: Header
    echo ===================================================
    echo        Personal Info Report - %date% %time%
    echo ===================================================
    echo.

    :: Current User Info
    echo [Current User]
    echo --------------------------------------
    echo Username: %USERNAME%
    echo User Domain: %USERDOMAIN%
    echo User Profile Path: %USERPROFILE%
    echo.

    :: All User Accounts
    echo [All User Accounts]
    echo --------------------------------------
    net user
    echo.

    :: Environment Variables (includes user-specific paths)
    echo [Environment Variables]
    echo --------------------------------------
    set
    echo.

    :: Network Configuration (IP, MAC, etc.)
    echo [Network Configuration]
    echo --------------------------------------
    ipconfig /all
    echo.

    :: WLAN Profiles (Wi-Fi Networks and Passwords)
    echo [WLAN Profiles]
    echo --------------------------------------
    netsh wlan show profiles
    echo.
    echo [WLAN Profile Details with Keys]
    echo --------------------------------------
    for /f "tokens=2 delims=:" %%i in ('netsh wlan show profiles') do (
        set "profile=%%i"
        set "profile=!profile:~1!"
        if not "!profile!"=="" (
            echo Profile: !profile!
            netsh wlan show profile name="!profile!" key=clear
            echo.
        )
    )

    :: User Directory Listing (Documents, Desktop, etc.)
    echo [User Directory Listing]
    echo --------------------------------------
    dir "%USERPROFILE%" /a /s /p 2>nul
    echo.

    :: Recently Accessed Files (via Recent folder)
    echo [Recent Files]
    echo --------------------------------------
    dir "%APPDATA%\Microsoft\Windows\Recent" /a /s /p 2>nul
    echo.

    :: Installed Software (User-Installed Programs)
    echo [Installed Software]
    echo --------------------------------------
    wmic product get Name, Version /format:list
    echo.

    :: Running Processes (Potentially User-Initiated)
    echo [Running Processes]
    echo --------------------------------------
    tasklist /nh
    echo.

    :: System Serial Number and BIOS (Device Identification)
    echo [BIOS and Serial Number]
    echo --------------------------------------
    wmic bios get Manufacturer, SerialNumber, Version /format:list
    echo.

    :: Footer
    echo ===================================================
    echo        End of Report - Generated by Cyberphoenix
    echo ===================================================
) > "%outputFile%"

:: Exit silently
exit

endlocal